services:
  app:
    container_name: sleep-tracker-app
    build:
      context: .
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "4000:3000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
      REDIS_URL: redis://redis:6379/0
      CACHE_URL: redis://redis:6379/1
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:3000/up"]
      interval: 10s
      timeout: 10s
      retries: 5

  db:
    container_name: sleep-tracker-db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    container_name: sleep-tracker-redis
    image: redis:7
    command: redis-server

  sidekiq:
    container_name: sleep-tracker-sidekiq
    build:
      context: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    environment:
      REDIS_URL: redis://redis:6379/0
      CACHE_URL: redis://redis:6379/1

  pgadmin:
    container_name: sleep-tracker-pgadmin
    image: dpage/pgadmin4:7
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pg_data:
